### ISSUE TITLE
Electrification layer

### ISSUE THREAD

**Issue by rurseekatze** [OpenRailwayMap/OpenRailwayMap#124]
Add a separate layer which visualizes electrification of railroads. It should consider the following tags:
- `electrified=yes/no/contact_line/rail/ground-level_power_supply`
- `voltage=*`
- `frequency=*`
- `electrified:rail=top/side/bottom`
- `railway:signal:electricity:*=*`
- `deelectrified=yes/contact_line/rail`
- `railway=isolated_track_section`
- `railway:main_switch_off=yes`
- `railway:lower_pantograph_section=yes`
- `railway=power_supply`
- `railway:electricity=joint` and `railway:electricity:jumpering=jumpered/possible/no`

**Comment by JJJWegdam** [comment]
**Proposal for rendering traction systems**
In this style, railways have coloured through their voltage/frequency according to the world's standard systems [[1]](http://en.wikipedia.org/wiki/List_of_current_systems_for_electric_rail_traction). The downside is that other systems [[2]](
http://en.wikipedia.org/wiki/List_of_current_systems_for_electric_rail_traction#Systems_using_non-standard_voltages) will be displayed in black. 
Another method would be to use smaller color intervals in order to cover the whole spectrum of voltages. Downsides would be that small differences (600 V vs 750 V within Rotterdam for example) might get lost and that different frequencies can't be mapped at all (which is a problem at 25 kV). For these reasons I prefer the method described below.

![Alt Text](http://puu.sh/gYIGq/dbdd25dc5d.png)


**Proposal for rendering Dutch electrical signs**
The Netherlands has some specific signs for traction like described in an ORM wiki [section](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging_in_Netherlands#Pantograph_directions). I'd propose to render 306a (turn off the main switch) at high zoom levels; this because it is (in the Netherlands) present in all combinations of electrical signs. For example: at several Dutch moveable bridges a piece of catenary is not present. Before the train driver is asked to lower the pantograph, allways a sign with turning off the main switch is displayed. This to prevent an electric arc (which damages the catenaries and pantograph).
Voltage switches and neutral sections are simply displayed by the tracks and other signs are allways in the vicinity of a 306a. Therefore I would advice to render these signs only at lower zoom levels.

![Alt Text](https://wiki.openstreetmap.org/w/images/thumb/e/ea/Dutch_railway_traction_signs.png/1024px-Dutch_railway_traction_signs.png)

**Comment by DerDakon** [comment]
See branch electricity-layer in my fork.

**Comment by DerDakon** [comment]
Some of these signals (e.g. 306a, 307a) look very similar to their German counterparts, so they could just use the same icon. What is otherwise missing in the el-layer?

**Comment by JJJWegdam** [comment]
If they are very similar it is fine to use the same icon, in my opinion. Good to see that there is such progress.

What would be missing is rendering of overhead wire supports. The Netherlands has open absolute data available of all its supporting portals and posts, which I would happily import if tagging and rendering is available.

**Comment by DerDakon** [comment]
Is there a good overview about these signal icons and how they are tagged? The tagging page looks unfinished.

**Comment by DerDakon** [comment]
The MapCSS layer is available for a long time in JOSM now. The new CartoCSS website now also has the electrification layer. Everything missing should be filed as new bug reports or PRs.
