### ISSUE TITLE
Rendering Dutch train protection systems

### ISSUE THREAD

**Issue by JJJWegdam** [OpenRailwayMap/OpenRailwayMap#513]
Currently, the signalling layer only renders the train protection systems that are in use in Germany. The issue which will be adressed here consists of 2 parts.

**Rendering the Dutch systems and their tags**
Currently, the following tags for the heritage system Automatische TreinBeïnvloeding (automatic train influencing) are in use:
The general ATB tag - `railway:atb=yes`
ATB Eerste Generatie (first generation) - `railway:atb-eg=yes`
ATB Verbeterde Versie (improved version) - `railway:atb-vv=yes`
ATB Nieuwe Generatie (new generation) - `railway:atb-ng=yes`
The ETCS tags are present aswell:
ETCS level 1 - `railway:etcs=1`
ETCS level 2 - `railway:etcs=2`
Advise 1: the current tagging is inconsistent; either ETCS should be tagged like `railway:etcs-2=yes` or ATB should be tagged like `railway:atb=yes` and `railway:atb:eg=yes`. I cannot fix the previous issue, but I still propose that the Dutch systems are rendered aswell.

**Rendering combined systems**
As shown in the image below, the Netherlands has several railways with multiple train protection systems. The railways between Amsterdam-Utrecht and Zwolle-Lelystad are have aswell ATB as ETCS installed, in order to enable higher operating speeds, becauseATB allows up to only 140 km/h. ATB+ allows up to 160 km/h, but is basically a hack consisting of ATB-EG and ATB-NG combined (and should therefore not have a seperate tag!). In the future, the problem of rendering multiple signalling systems will become more visible; as the image shows, the government has planned to equip many more lines with ETCS along with the existing ATB.
Advise 2: the migration towards ETCS will make it increasingly important that railway lines with multiple train protection systems are rendered as such.

![alt text](https://wiki.openstreetmap.org/w/images/5/5e/NL_ATB_ETCS.png)

**Comment by bigbug21** [comment]
Changing the tagging scheme for ETCS ("railway:etcs-2=yes") is a really good it since there are some lines that support both ETCS Level 1 and ETCS Level 2 (such as HSL 3 and HSL 4).

**Comment by DerDakon** [comment]
In Germany all lines that are equipped with LZB also have PZB, and most of those that will get ETCS will have either or both, too. For now we only show the highest system, as the view will become too crowded otherwise.

For the colors to use for e.g. the Netherlands just propose color(s).

**Comment by rurseekatze** [comment]
Concerning the ATB tags I would propose the following scheme:

* `railway:atb=yes` - general tag
* `railway:atb=eg` - ATB Eerste Generatie
* `railway:atb=vv` - ATB Verbeterde Versie
* `railway:atb=ng` - ATB Verbeterde Versie

@JJJWegdam Am I right with my assumption that a track can be equipped just with one version of ATB? In that case I would propose the scheme above. Otherwise it would be possible to tag a track e.g. with `railway:atb=eg` AND `railway:atb=ng` which would be wrong.

**Comment by rurseekatze** [comment]
> Changing the tagging scheme for ETCS ("railway:etcs-2=yes") is a really good it since there are some lines that support both ETCS Level 1 and ETCS Level 2 (such as HSL 3 and HSL 4).

I did not know that. I assumed that there are not different ETCS levels on the same track. The current scheme says that the value should be only one level. But for tagging multiple levels this is not appropriate and we need another scheme.

But I am not fully convinced of your proposal of `railway:etcs-2=yes` because putting the level into the key makes it sometimes more difficult to use the data. It should always be avoided to put information into the key, if possible. If you plan to query all tracks with any level of ETCS, there are just these possibilities with your proposal:

* Querying features with a key containing the substring `railway:etcs` (such queries are not possible in all databases, also substring queries are not performing very well)
* Querying features with `railway:etcs=yes` or `railway:etcs-1=yes` or `railway:etcs-2=yes` or `railway:etcs-3=yes` (supported in all applications, but requires longer queries)
* Tagging all tracks with the additional tag `railway:etcs=yes` (very redundant)

Also your proposal is not compatible to the current scheme, so it would require retagging, documentation updates and updating applications (not just our code, but also possible users of OSM railway data).

An alternative would be using semicolon-separated lists of ETCS levels as value (e.g. `railway:etcs=1;2`). Advantages of this solution are that it does not require any retagging, mechanical edits with discussions, documentation updates, etc. Also this makes it easier to query all tracks with any ETCS level. On the other hand here it is required to do a substring query for the key to check if a track is equipped with a certain ETCS level.

Has anybody here feedback? Which solution for tracks with multiple ETCS levels do you prefer?

**Comment by DerDakon** [comment]
I strongly prefer list solutions, especially as they are already quite common in railway tagging, e.g. for signal states. I personally would throw all systems in one railway:train_protection key with a list of values. Sure, that would require retagging again, so let's stop introducing more "yes only" keys (i.e. set to yes if a feature is there, not set at all otherwise).

**Comment by rurseekatze** [comment]
>For the colors to use for e.g. the Netherlands just propose color(s).

Yes, just propose any color (maybe those who are common in NL for these systems). But I would prefer that they differ from the current colors in Germany (orange, red, blue) so that it is possible for the user to distinguish the different systems on the map.

**Comment by rurseekatze** [comment]
> I strongly prefer list solutions, especially as they are already quite common in railway tagging, e.g. for signal states. I personally would throw all systems in one railway:train_protection key with a list of values. Sure, that would require retagging again, so let's stop introducing more "yes only" keys (i.e. set to yes if a feature is there, not set at all otherwise).

I am also not a fan of these yes-tags and try to avoid them if possible, but for systems such as ETCS they offer the possibility to tag `=yes` as a first version if the level is unknown and specify the level later by replacing `yes` by other values.

But your idea of throwing all systems into a single tag has a great disadvantage: It would not be possible to tag a track explicitly as being not equipped with a certain system.

**Comment by JJJWegdam** [comment]
> Yes, just propose any color (maybe those who are common in NL for these systems)

There are no specific common colors for the Dutch systems. The only logical colors would be shades of orange ([for orange is the national color](https://www.google.nl/search?q=koningsdag&espv=2&biw=1440&bih=775&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj-_sOBpe7MAhWFIMAKHehVDRUQ_AUIBigB)). This would require a change of PZB render color, but I think it's worth it. With so many countries having so many different systems, it would be beneficial to give all countries a color (with shades of the color if needed).

**Comment by DerDakon** [comment]
Shades are rather hard to distinguish. The orange we used for  PZB ist just "a darker yellow" as most rail equipment that is installed in the tracks is yellow in Germany.

The colors also do not have to be unique, e.g. the colors used in the Netherlands, Poland, and Switzerland can all be the same as those countries do not share borders or systems.

Lets focus on the NL colors here and move the tagging discussion to the mailing list.

**Comment by JJJWegdam** [comment]
> as most rail equipment that is installed in the tracks is yellow in Germany.
Same as in the Netherlands.. ;)

**Comment by rurseekatze** [comment]
> There are no specific common colors for the Dutch systems. The only logical colors would be shades of orange (for orange is the national color). This would require a change of PZB render color, but I think it's worth it. With so many countries having so many different systems, it would be beneficial to give all countries a color (with shades of the color if needed).

It should be possible that multiple systems have the same color, but in that case these countries should be separated. For neighbouring countries this should be avoided, otherwise it is not possible to distinguish the systems at the borders.

Using Oranje for Dutch systems would make sense, but this requires changing the current color scheme. I am not a fan of such changes because users might be used to the current scheme and be confused if the color scheme changes suddenly.

> Lets focus on the NL colors here and move the tagging discussion to the mailing list.

:+1:

**Comment by JJJWegdam** [comment]
@rurseekatze 
> Concerning the ATB tags I would propose the following scheme:
railway:atb=yes - general tag
railway:atb=eg - ATB Eerste Generatie
railway:atb=vv - ATB Verbeterde Versie
railway:atb=ng - ATB Verbeterde Versie

I would recommend the following descriptions for the legend:
railway:atb=yes - ATB
railway:atb=eg - ATB Eerste Generatie
railway:atb=ng - ATB Nieuwe Generatie
railway:atb=vv - ATB Verbeterde versie
This orders the systems in age, removes a typo and removes the capital from 'versie' ([as is correct in Dutch](https://nl.wikipedia.org/wiki/Automatische_treinbe%C3%AFnvloeding#ATB_Verbeterde_versie)).

> @JJJWegdam Am I right with my assumption that a track can be equipped just with one version of ATB? In that case I would propose the scheme above. Otherwise it would be possible to tag a track e.g. with railway:atb=eg AND railway:atb=ng which would be wrong.

This is incorrect, but only due to a special case. An ATB-hack, named ATBM+ has both the EG track circuit and NG beacons. The EG track circuit sends a 140 km/h signal and the NG beacons send an overriding 160 km/h message (for delayed diverted ICE's (Frankfurt-Amsterdam)). This only is used on a single line and in special cases.

**Comment by JJJWegdam** [comment]
> Using Oranje for Dutch systems would make sense, but this requires changing the current color scheme. I am not a fan of such changes because users might be used to the current scheme and be confused if the color scheme changes suddenly.

I agree that the scheme should not be changed too often. However, Germany now 'owns' two primary colors. This can contribute to the problem of running out of colors in the long term. I therefore propose to alter the PZB anyway. 

**NL**
The Dutch systems receive orange, being the national color.
- ATB is treated the same as ATB-EG. It feeds continuous information to the train through it's coded track circuits.
- ATB-NG uses balises instead of coded track circuits.
- ATB-Vv is an addition to the continuous information feed from ATB and the only improvement is forced stops before red signals. These occur less often than balises and impact the train more heavily. 

**DE**
The German systems receive red, being the DB color. 
- PZB gives information through fixed points
- LZB gives information continuously

**EU**
The ETCS Levels receive blue and yellow, from the European flag. 
- ETCS Level 1 uses Eurobalises, but does not use GSM-R. Therefore Euroloops are advised at busy tracks and interlockings.
- ETCS Level 2 also uses GSM-R and therefore gets rid of the Euroloops.
- ETCS Level 3 incorporates a Train Integrity Monitor and allows for much less sophisticated Eurobalises (only providing static track information).

The different systems receive different line styles according to the background of the system. This leads to the following render proposal. I look forward to your comments and hope that it will be implemented after agreement has been reached.

![alt txt](http://puu.sh/p6NlW/7c4831b3ee.PNG)

**Comment by DerDakon** [comment]
I think your base assumption is bad here, so let's start with what I think is a good overall design:
 * adjacent railway systems (i.e. mostly countries) use different colors for their usual protection systems
 * systems that are used on the same track or on neighboring tracks have different colors
 * different systems (not system versions) should not only differ only by casing

Most people will look at things on a rather local scope, so if e.g. all German systems are red you don't win anything inside of Germany (i.e. my assumed common case), but only on the borders. Given the size of the Netherlands this is a much more common case for you than for me, granted ;)

ETCS levels are discussed in #508, so I would exclude that here. I think we all agree that blue is a good color choice for ETCS for various reasons, so I take that as granted.

We could now come up with criteria on when we use e.g. casing and when not, lets say for things that only influence the train at points like PZB does. As far as I understand ATB is more similar to LZB than to PZB. Because of the "local stop" one could use it as addition to the ATB color for ATB-Vv.

I don't argue to use orange for ATB, if that's the final point, but I don't think using red for both common systems in Germany (or anywhere else) is a good idea. Also some systems are used at entirely different places if a local train manufacturer wins an abroad bidding, e.g. LZB uses in Malaysia because of Siemens trains.

**Comment by JJJWegdam** [comment]
@DerDakon: I think
> Also some systems are used at entirely different places if a local train manufacturer wins an abroad bidding, e.g. LZB uses in Malaysia because of Siemens trains.

contradicts with

> Most people will look at things on a rather local scope, so if e.g. all German systems are red you don't win anything inside of Germany

Please regard the metros of Rotterdam and Amsterdam that use LZB, which makes different colors per national system favorable even within a small country like the Netherlands. Choosing to render like this emphasizes the incompatibility and prevents national systems from being mixed up with foreign systems. Therefore I disagree with the earlier statement of @rurseekatze 

> It should be possible that multiple systems have the same color, but in that case these countries should be separated.

**Comment by DerDakon** [comment]
Well, he is right, but it has to be done with caution. The European countries have mostly their own systems, and if anyone from abroad wants to sell anything here they have to adapt the trains to the country. Less developed (in terms of railway) countries may not have something set at all, so it may be common for a European manufacturer to sell "their" system to somewhere else.

For the moment I would say that systems from e.g. the Netherlands, Poland, and Italy may all have the same color, as it would be uncommon for them to meet at any place. For the moment we would probably start with the Netherlands, which will likely become orange. The discussion if a specific color is a good choice or not can be done when the next things come up for integration, but you are right: one has to take the worldwide distribution of the local railway manufacturers into account.
