### ISSUE TITLE
Rendering "no train protection" for tramways/straßenbahn.

### ISSUE THREAD

**Issue by STemplar** [OpenRailwayMap/OpenRailwayMap#562]
Hello to all, I am new to this forum and openrailwaymap.org but started along with tagging. Tramways/straßenbahn (often) does not have a train protection system. How do we tag them? I've tagged the Rotterdam tramway network as "railway:lzb=no" but that didn't work.

**Comment by DerDakon** [comment]
Please discuss tagging on the mailing list, this issue tracker is only about the software implementation. I would something like "railway:train_protection=none".

**Comment by rurseekatze** [comment]
The problem with visualizing the information "without any train protection" is that the current tagging schema just allows it to tag the existing systems, but not explicitely tag the not existing systems.

Dropping those tags could also be interpreted that the installed protection systems are not mapped or unknown yet. But tagging `railway:lzb=no` also does not make much sense because then you could tag that tramway track with every train protection on the world as `no`.

There have been [discussions about that topic in the past](http://lists.openrailwaymap.org/archives/openrailwaymap/2014-November/000177.html). I would recommend to discuss on our [mailing list](http://lists.openrailwaymap.org/) or in the [IRC channel](http://irc.openstreetmap.org/).
