### ISSUE TITLE
Getting the pure railway track data only

### ISSUE THREAD

**Issue by blokhin** [OpenRailwayMap/OpenRailwayMap#624]
Dear Maintainers and Railroad Fans,

is it possible to obtain the trackmaps in machine-readable format (_e.g._ vector images, JSON _etc._)?
That means, pure railroad maps, without any server rendering, without OSM layers, just the only network graph. The aim is to practice some data mining using graph traversal algorithms.

Thanks for your time spent on this wonderful project!

**Comment by Nakaner** [comment]
OpenRailwayMap only uses data of the OpenStreetMap project. The full planet dump and its updates can be downloaded at https://planet.openstreetmap.org. Daily updated country extracts are available at https://download.geofabrik.de

The planet itself is quite huge, that's why I recommend you to start with a country extract.

You can extract all railway data using the `tags-filter` command of the [Osmium Tool](https://osmcode.org/osmium-tool/). Its `export` command can create GeoJSON. There are also [companies](https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services) which do the data processing for you.

I close this issue because it isn't an issue of this software project. You are free to ask questions on [our mailing list](https://lists.openrailwaymap.org/lists/listinfo/openrailwaymap), any other suitable [OpenStreetMap mailing list](https://lists.openstreetmap.org/listinfo) or [IRC](https://wiki.openstreetmap.org/wiki/IRC).
