### ISSUE TITLE
ETCS under construction - color

### ISSUE THREAD

**Issue by mmosteck** [OpenRailwayMap/OpenRailwayMap#631]
Currently "_ETCS under construction_" layer is the same color as "_ETCS_" and on low zoom level dashed line is **almost invisible** thus it is barely distinguishable from "_ETCS_". 
On some zoom levels dashing **disappears entirely** and there is completely no difference between "_ETCS_" and "_ETCS under construction_".

I would like to suggest change of "_ETCS under construction_" layer to **light blue** color (it makes sense since _ETCS_ is deep[er] blue) or some other one, could be anything but red and yellow.

Another option would be to increase dashed line spacing, but I'm afraid that it wouldn't work on particular zoom levels as it would merge itself anyways.

**Comment by Nakaner** [comment]
Increasing the line spacing won't help either. Parallel lines rendered with a dashed line style will merge to one wide undashed line when you zoom out. The rendering software (all of seem to have this issue) renders each line independently and starts the dashing at the first vertex. If two parallel lines are straight (e.g. two parallel straight tunnels), this does not matter because their dashing will be parallel, too. But if the tunnel has a curve, the inner line is shorter than the outer one.

There are two solutions. Either drop dashing at all or use a preprocessed geometries for medium and low zoom levels where two parallel tracks are conflated to one single track.
