### ISSUE TITLE
Signaling convention for Russian railroads

### ISSUE THREAD

**Issue by andrewzolotukhin** [OpenRailwayMap/OpenRailwayMap#796]
Hi all, first of all want to thank you for the great project!

I'm just wondering if we have some kind convention for signals post-soviet countries? I found documents describing German signaling system and some other countries, but not Russia and other post-soviet countries. 

I'd like to work on that and don't want to reinvent the wheel. So first of all I want to understand if we already have some standards or people who work on it.

**Comment by DerDakon** [comment]
I would suggest starting a page in the [wiki](https://wiki.openstreetmap.org/) in your personal namespace that collects the available information. Then write an email to the [mailinglist](mailto:openrailwaymap@openrailwaymap.org) and start discussing a scheme how this could be tagged. The [archive shows](https://lists.openrailwaymap.org/mailman3/hyperkitty/list/openrailwaymap@openrailwaymap.org/thread/2EPHTNQ2LHJ4KFXCB42IBSAFXV4JREIF/) that there has already been interest in this.

I'll close this issue here as this tracker is not for discussing the way of tagging, at the end this is just the implementation of the approved way of tagging, even if the people involved may overlap.
