### ISSUE TITLE
Site down due to DNS issues

### ISSUE THREAD

**Issue by FrankyBoy** [OpenRailwayMap/OpenRailwayMap#808]
Looks like openrailwaymap.org is down due to DNS issues. Getting DNS_PROBE_FINISHED_NXDOMAIN in Chrome and the equivalent message in Firefox. Dig/nslookup also return no data. 

Sorry I can't really add much more infos, debugging DNS is not part of my skillset yet 😅

**Comment by Nakaner** [comment]
Thank you for the report.

The error was my fault. The domain has been (and is) registered via INWX for a couple of years. However, two personal virtual servers at 1blu have been the nameservers for the domain. Because I wanted to get rid of self-hosting Bind DNS server, I copied all the entries into the INWX web interface a few days ago. Today, I stopped Bind on the nameservers. Unfortunately, I forgot to change the nameserver at the INWX web interface to their nameservers (ns.inwx.de, ns2.inwx.de, ns3.inwx.de).

I changed that entry a few minutes ago. In order to get things working a little bit quicker, I started the old nameservers temporarily.
