### ISSUE TITLE
Display yards mapped as areas

### ISSUE THREAD

**Issue by marioxcc** [OpenRailwayMap/OpenRailwayMap#840]
Currently ORM only displays yard names for nodes. Areas are more accurate than single nodes in describing a yard. A single node is unclear as to the extent of the yard, especially when a yard has several classification/arrival/departure bowls. Display yard mapped as areas, in addition to yard mapped as nodes for compatibility with existing data

**Comment by DerDakon** [comment]
The tagging is described in https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Operating_sites and the idea is basically: put the node where you think the name of the site would show up best. If you want the area also mapped use e.g. landuse=railway and operating site relations. The problem otherwise would be that there is no good way to find the place where to show the name. While this is easy for simple geometries it would be close to impossible to find a good way for everything that has "holes".

If you have a better idea please use the normal OSM proposal process to suggest different tagging.

**Comment by marioxcc** [comment]
Here is a better idea and it is an implementation matter, so no OSM proposal: Compute the topological thinning, then put the name centered on the point in the topological thinned feature that is farthest from the edge of the original feature.
